1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
#append
list = [1,2,3,4,5]
list.append(6)
list

[1, 2, 3, 4, 5, 6]

In [ ]:
#extend
list = [1,2,3,4,5]
list.extend([5,6,7])
list

[1, 2, 3, 4, 5, 5, 6, 7]

In [ ]:
#insert
list = [1,2,3,4,5]
list.insert(0,2)
list

[2, 1, 2, 3, 4, 5]

In [ ]:
#remove
list = [1,2,3,4,5]
list.remove(5)
list

[1, 2, 3, 4]

In [ ]:
#pop
list = [1,2,3,4,5]
list.pop()
list

[1, 2, 3, 4]

In [ ]:
#clear
list = [1,2,3,4,5]
list.clear()
list

[]

In [ ]:
#index
list = [1,2,3,4,5]
list.index(2)

1

In [ ]:
#sort
list = [1,2,7,6,5]
list.sort()
list

[1, 2, 5, 6, 7]

In [ ]:
#reverse
list = [1,2,3,4,5]
list.reverse()
list

[5, 4, 3, 2, 1]

In [ ]:
#count
list = [1,2,3,4,5]
list.count(5)

1

2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
names = ("bhuvan","pavan","dhavan")
type(names)

tuple

In [ ]:
names[1] = "rahul"

TypeError: 'tuple' object does not support item assignment

A tuple is designed to be immutable (unchangeable). Once a tuple is created,
you can access its elements, but you cannot add, remove, or modify them.

In [ ]:
print(names)

('bhuvan', 'pavan', 'dhavan')

3 . Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
a = {10,20,(30,40),30,40,40,40,30,10}
type(a)

set

In [ ]:
print(a)

{20, 40, 10, 30, (30, 40)}

A set stores only unique (distinct) values.
When duplicate values are added to a set, Python automatically removes them.

------------------------------

4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
dict = {
    "name" : "bhhvn",
    "age" : 23,
    "city" : "DWD"

}

In [ ]:
type(dict)

dict

In [ ]:
dict.update({"age" : 24 ,"email": "bsmmadihalli@gmail.com"})
print(dict)

{'name': 'bhhvn', 'age': 24, 'city': 'DWD', 'email': 'bsmmadihalli@gmail.com'}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input("Enter your age"))
if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter your age23
You are eligible to vote

6. Given a 'marks' variable, print the grade:- 90 and above: 'A'- 75–89: 'B'- 50–74: 'C'- Below 50: 'Fail'

In [ ]:
marks = int(input("Enter your marks"))
if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

Enter your marks90
A



7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num = int(input("Enter a number"))
if num > 0:
    if num % 2 == 0:
        print("Positive and even",num )
    else:
      print("Positive and odd",num)

elif num < 0:
  if num % 2 == 0:
    print("Negative and even",num)
  else:
     print("Negative and odd", num)

elif num == 0:
    print("Zero",num)

Enter a number-34
Negative and even -34

8. Create:- A scalar using np.array(5)- A 1D array with values 1 to 5- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(5)
array_1D = np.array([1,2,3,4,5])
array_2D = np.array([[10,20,30],[40,50,60]])

print(scalar)
print(array_1D)
print(array_2D)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]

9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
import numpy as np
#np.random.randint(low, high, size)

In [ ]:
arr = np.random.randint(0, 101, size=(4, 4))
arr

array([[47, 42, 63, 20],
       [17, 96, 58, 50],
       [ 2, 18, 41, 23],
       [18, 52,  3, 98]])

10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

In [ ]:
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:- Use .info(), .describe()- Select 'Name' and 'City' columns- Drop 'City' column- Fill any missing values in 'Salary' column with the mean- Remove any duplicate rows

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva',
             'Frank', 'Grace', 'Henry', 'Ivy', 'Bob'],
    'Age': [25, 30, 35, 28, 40, 32, 27, 45, 29, 30],
    'City': ['New York', 'Chicago', 'Boston', 'Seattle', 'Miami',
             'Dallas', 'Denver', 'Austin', 'Phoenix', 'Chicago'],
    'Salary': [50000, 60000, np.nan, 55000, 70000,
               62000, np.nan, 80000, 58000, 60000]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

      Name  Age      City   Salary
0    Alice   25  New York  50000.0
1      Bob   30   Chicago  60000.0
2  Charlie   35    Boston      NaN
3    David   28   Seattle  55000.0
4      Eva   40     Miami  70000.0
5    Frank   32    Dallas  62000.0
6    Grace   27    Denver      NaN
7    Henry   45    Austin  80000.0
8      Ivy   29   Phoenix  58000.0
9      Bob   30   Chicago  60000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

             Age       Salary
count  10.000000      8.00000
mean   32.100000  61875.00000
std     6.226288   9295.73635
min    25.000000  50000.00000
25%    28.250000  57250.00000
50%    30.000000  60000.00000
75%    34.250000  64000.00000
max    45.000000  80000.00000

In [ ]:
df[['Name', 'City']]

      Name      City
0    Alice  New York
1      Bob   Chicago
2  Charlie    Boston
3    David   Seattle
4      Eva     Miami
5    Frank    Dallas
6    Grace    Denver
7    Henry    Austin
8      Ivy   Phoenix
9      Bob   Chicago

In [ ]:
df_no_city = df.drop('City', axis=1)

In [ ]:
salary_mean = df['Salary'].mean()

In [ ]:
salary_mean

np.float64(61875.0)

In [ ]:
df['Salary'] = df['Salary'].fillna(salary_mean)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

      Name  Age      City   Salary
0    Alice   25  New York  50000.0
1      Bob   30   Chicago  60000.0
2  Charlie   35    Boston  61875.0
3    David   28   Seattle  55000.0
4      Eva   40     Miami  70000.0
5    Frank   32    Dallas  62000.0
6    Grace   27    Denver  61875.0
7    Henry   45    Austin  80000.0
8      Ivy   29   Phoenix  58000.0